deploy:
  on:
    condition: "$TOXENV == py35"
    repo: ayemos/osho
    tags: true
  user: ayemos
  provider: pypi
  distributions: sdist bdist_wheel
  password:
    secure: XjyJNB2LTQS/vvFsnXgfLFIuR3a1kOTpmDW8DE+CzVBRf/W6qCKnTmWyymHnMXRE0yoahxagmx0WZiTGcl59vB3DH0TbZhuQRn1fk0Nj7BkwpnbTHGr4S9mRDRKB0k6GOg2zO2cTlxLQKTTDTYA00nbtjFfGjIL/nlnBg4HGkHy4/cDmEGbYUuOLe70QhBHJ+2pOl3EKe7fuIdtzNeookHQ7oMzIPwMENyUX1hTaCaq2PQIr8zbShdJ50wJBWoLJZsBWMD5kIRrgBVlHYYrBHGLEcSy40ePPLKh+EhRQjmsMvPdXe++gxIvGY/uffJ7EAl900NvUI4ZWKCNfizYzsW6NEk3xc0MNMRqnflsVm+N2n9ti/VEQC8aQOw1v77RmmVpx3Jqle5Jliviz5LwjJ/g6sXdl3A+9vX51y+5TA2LuwoN7wdWlyA7xg7EBBG0/SJ/k3/xX6cySo8XWcVi5QNPqtZ3a6ce+FXm8tj6fbEtjOb/GpMUD/lKYjDPWr12Er1E+KLnLoiMGqXnrSSvy+xAZV/InY8cQxVs3dFt6sN3lQKW0Pyyes2Mmna/oaNZFAOY4nUN8vvqvcaTyHoRmuvdOknLnpLV0G3O7Fq1ZP++WgxnYK39FdgPepL09L2oUMYDOjUcLGbH2LmquvMF5SImYu/yGw8dnMjWQfI6E7Zo=
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py27
install: pip install -U tox
language: python
python: 3.5
script: tox -e ${TOXENV}
